application: cs-todo
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /styles
  static_dir: static/styles
- url: /scripts
  static_dir: static/scripts
- url: /images
  static_dir: static/images
- url: /.*
  script: _go_app
